### ISSUE TITLE
Talents 

### ISSUE THREAD

**Issue by KaiderWeise** [mkscho63/sta#33]
**Describe the bug**
It is not possible to change talents. After clicking on the +, "New Talent" appears but nothing happens when the Edit button is pressed. 

**To Reproduce**
1. Go to Character Sheet / Talents Section
2. Click on Edit
3. The Talent can´t be edited

**Expected behavior**
The talent should be editable

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Firefox, Edge

**Comment by mkscho63** [comment]
Thanks for sending in this report. I attempted to recreate this bug but was unable to. I have included a gif of the operation successfully happening on my local instance of the system. Is there something that I did that didn't mirror your workflow?

One thing to note that has gotten me a lot of times while setting up characters is that sometimes the Edit Talent window gets stuck behind the character sheet I'm working on. I have to move the character sheet over to see it behind. Clicking the edit button again won't reopen an edit talent window if it is already detected to be open. I show an example of this at the end of my .gif file. If that's not the case though, tell me if I did something different than you in my example. I'll keep an eye out for this as I'm working further but right now I'll wait to hear back from you before hitting this more on direct investigating.

![Image of bug](https://i.imgur.com/fabwJuh.gif)

**Comment by KaiderWeise** [comment]
Unfortunately, this is not the case for me. After pressing F12 I get the following error message. Does this help? 

Error: 

foundry.js:4481 TypeError: An error occurred while rendering STATalentSheet 28: Cannot use 'in' operator to search for 'title' in Type
    at getProperty (foundry.js:1339)
    at Localization.localize (foundry.js:5901)
    at Object.localize (foundry.js:6076)
    at Object.c (handlebars.min.js:27)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29), <anonymous>:21:149)
    at c (handlebars.min.js:27)
    at d (handlebars.min.js:27)
    at e (handlebars.min.js:28)
    at foundry.js:5992
    at async STATalentSheet._renderInner (foundry.js:4661)

**Comment by mkscho63** [comment]
Yes it does. Are you adding a Talent to a character/starship/smallcraft?

**Comment by KaiderWeise** [comment]
It is probably due to the language selected in the Core Settings. The talents work in English, but unfortunately not in German.

**Comment by nerdlibfront** [comment]
I fixed that in #38
@mkscho63 if you accept the request, the talents should work again in german.
Tested it with a custom system i uploaded to Forge.

**Comment by KaiderWeise** [comment]
The Problem is back again...

foundry.js:4481 TypeError: An error occurred while rendering STATalentSheet 28: Cannot use 'in' operator to search for 'title' in Type
    at getProperty (foundry.js:1339)
    at Localization.localize (foundry.js:5901)
    at Object.localize (foundry.js:6076)
    at Object.c (handlebars.min.js:27)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29), <anonymous>:21:149)
    at c (handlebars.min.js:27)
    at d (handlebars.min.js:27)
    at e (handlebars.min.js:28)
    at foundry.js:5992
    at async STATalentSheet._renderInner (foundry.js:4661)

**Comment by mkscho63** [comment]
I have not merged the fix in yet, it is on the develop branch if you want to download it manually. I have been caught up trying to get the system ready for the 0.8.x branches and that has proved kinda challenging unfortunately. Hopefully I can get this all up to date in the master branch soon though. Apologies for the delay.
